version: '3.2'

services:

  eshop-api:
    build:
      context: ./eshop-api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - eshop-discovery
      - composite-category
      - composite-product
      - core-user

  eshop-discovery:
    build:
      context: ./eshop-discovery
      dockerfile: Dockerfile
    ports:
      - 9002:9002

  eshop-edge:
    build:
      context: ./eshop-edge
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    depends_on:
      - eshop-discovery

  core-user:
    build:
      context: ./core-user
      dockerfile: Dockerfile
    ports:
      - 8086:8086
    depends_on:
      - eshop-discovery

  core-product:
    build:
      context: ./core-product
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    depends_on:
      - eshop-discovery

  core-category:
    build:
      context: ./core-category
      dockerfile: Dockerfile
    ports:
      - 8084:8084
    depends_on:
      - eshop-discovery

  composite-product:
    build:
      context: ./composite-product
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - eshop-discovery
      - core-product
      - core-category

  composite-category:
    build:
      context: ./composite-category
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - eshop-discovery
      - core-product
      - core-category
