version: '3.2'
services:
  eshop-api:
    build: ./eshop-api
    ports:
      - 8080:8080
  eshop-discovery:
    build: ./eshop-discovery
    ports:
      - 9002:9002
  eshop-edge:
    build: ./eshop-edge
    ports:
      - 9001:9001
  core-user:
    build: ./core-user
    ports:
      - 8086:8086
  core-product:
    build: ./core-product
    ports:
      - 8085:8085
  core-category:
    build: ./core-category
    ports:
      - 8084:8084
  composite-product:
    build: ./composite-product
    ports:
      - 8082:8082
  composite-category:
    build: ./composite-category
    ports:
      - 8081:8081